#!/usr/bin/env perl
use Git::Hooks;
use Cwd;
use File::Basename qw( dirname );
use Path::Class;
use feature qw(say);

#-- get current directory
my $pwd = Cwd::cwd();
#say $pwd;
#my $sdir = dirname(dirname(Cwd::abs_path($pwd)));
my @files;
dir($pwd)->recurse(callback => sub {
    my $file = shift;
    if($file eq "$pwd/.git"){
       return ;
    }

    if(-d $file  && $file =~ /\.git$/) {
         push @files, $file->absolute->stringify;
    }
});

if(@files){
  say "You hava .git in follow directory,so you can not commit  .... ";  
  for my $file (@files) {
     say $file;
  }  
  
  exit 1;
}

run_hook(zsh, @ARGV);
